package repository

import (
	"context"
	"time"
)

// CronSchedule defines when a cron job should run.
type CronSchedule struct {
	Kind    string `json:"kind"`              // "at", "every", or "cron"
	AtMS    *int64 `json:"atMs,omitempty"`    // One-time execution timestamp (ms)
	EveryMS *int64 `json:"everyMs,omitempty"` // Interval in milliseconds
	Expr    string `json:"expr,omitempty"`    // Cron expression
	TZ      string `json:"tz,omitempty"`      // Timezone
}

// CronPayload contains the job execution payload.
type CronPayload struct {
	Kind    string `json:"kind"`               // Payload type (e.g., "agent_turn")
	Message string `json:"message"`            // Message content
	Deliver bool   `json:"deliver"`            // Whether to deliver
	Channel string `json:"channel,omitempty"`  // Target channel
	To      string `json:"to,omitempty"`       // Recipient
}

// CronJobState tracks the execution state of a cron job.
type CronJobState struct {
	NextRunAtMS *int64 `json:"nextRunAtMs,omitempty"` // Next execution time (ms)
	LastRunAtMS *int64 `json:"lastRunAtMs,omitempty"` // Last execution time (ms)
	LastStatus  string `json:"lastStatus,omitempty"`  // "ok" or "error"
	LastError   string `json:"lastError,omitempty"`   // Error message if failed
}

// CronJob represents a scheduled automation job.
type CronJob struct {
	ID             string       `json:"id"`
	Name           string       `json:"name"`
	Enabled        bool         `json:"enabled"`
	Schedule       CronSchedule `json:"schedule"`
	Payload        CronPayload  `json:"payload"`
	State          CronJobState `json:"state"`
	CreatedAtMS    int64        `json:"createdAtMs"`
	UpdatedAtMS    int64        `json:"updatedAtMs"`
	DeleteAfterRun bool         `json:"deleteAfterRun"` // Auto-delete after execution
}

// CronRepository defines the interface for cron job persistence.
type CronRepository interface {
	// GetJob retrieves a job by its ID.
	// Returns error if job is not found.
	GetJob(ctx context.Context, jobID string) (*CronJob, error)

	// ListJobs returns all jobs, optionally including disabled jobs.
	// If includeDisabled is false, only enabled jobs are returned.
	ListJobs(ctx context.Context, includeDisabled bool) ([]CronJob, error)

	// AddJob creates a new cron job.
	// The job ID should be pre-generated by the caller.
	AddJob(ctx context.Context, job *CronJob) error

	// UpdateJob updates an existing job.
	// Returns error if job is not found.
	UpdateJob(ctx context.Context, job *CronJob) error

	// DeleteJob removes a job permanently.
	// Returns error if job is not found.
	DeleteJob(ctx context.Context, jobID string) error

	// GetDueJobs returns all enabled jobs that are due for execution
	// (jobs where NextRunAtMS <= now).
	GetDueJobs(ctx context.Context, now time.Time) ([]CronJob, error)

	// UpdateJobState updates only the execution state of a job.
	// Used after job execution to update run times and status.
	UpdateJobState(ctx context.Context, jobID string, state CronJobState) error

	// GetNextWakeTime returns the earliest next run time across all enabled jobs.
	// Returns nil if no jobs are scheduled.
	GetNextWakeTime(ctx context.Context) (*time.Time, error)
}
